version: '3.6'

services:

  rabbit:
    image: rabbitmq:3-management
    restart: always
    environment:
        RABBITMQ_DEFAULT_USER: rabbit
        RABBITMQ_DEFAULT_PASS: hEgJVlql9cD2nmP6
    ports:
      - 5671:5671
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq
#    networks:
#      - providcy_net
    logging:
      options:
        max-size: "500k"
        max-file: "10"

volumes:
  rabbit_data:

#networks:
#  providcy_net:
#    name: providcy_net
