version: '3.4'

services:

  backend:
    container_name: backend
    image: backend:latest
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: password
    ports:
      - 8080:8080
    networks:
      - providcy_net
    logging:
      options:
        max-size: "500k"
        max-file: "10"

networks:
  providcy_net:
    external: true
