version: '3.6'

services:

  smbus:
    container_name: smbus
    image: smbus:latest
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
    logging:
      options:
        max-size: "500k"
        max-file: "10"
