version: '3.6'

services:

  node:
    container_name: node
    image: node:latest
    restart: always
    ports:
      - 7777:7777
      - 8888:8888
    volumes:
      - node_data:/usr/src/target/debug/db
    logging:
      options:
        max-size: "500k"
        max-file: "10"

volumes:
  node_data:
